### ISSUE TITLE
Don't include your input data/puzzle

### ISSUE THREAD

**Issue by ben-nour** [hnasheralneam/aoc2024#1]
Just a reminder not to share your input/data files! 

Advent of Code specifically requests you don't do this:

_**Can I copy/redistribute part of Advent of Code?** Please don't. Advent of Code is free to use, not free to copy. If you're posting a code repository somewhere, please don't include parts of Advent of Code like the puzzle text or your inputs. If you're making a website, please don't make it look like Advent of Code or name it something similar._

- [Advent of code](https://adventofcode.com/2024/about)

**Comment by hnasheralneam** [comment]
Thank you for letting me know! I'll remove them immediately. If you think I need to remove the past commits with the inputs included please let me know and I'll do that as well.

**Comment by hnasheralneam** [comment]
Fixed with [commit](https://github.com/hnasheralneam/aoc2024/commit/e2a5469a062ccdae0152040dd41c5df55422eab1) and [commit](https://github.com/hnasheralneam/aoc2024/commit/31753bf72315f5f52cfd788933d7fd10fb7028f8)
